// <auto-generated />
using System;
using Dars_5ososy_API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dars_5ososy_API.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702161523_CreateInitialTables")]
    partial class CreateInitialTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.Area", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("GovernorateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ArabicName = "Area 1",
                            EnglishName = "Area 1",
                            GovernorateId = 1L
                        });
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.AvailabilitySlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AreaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("EducationStageId")
                        .HasColumnType("int");

                    b.Property<int>("EducationSystemId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("EducationStageId");

                    b.HasIndex("EducationSystemId");

                    b.HasIndex("TeacherId");

                    b.ToTable("AvailabilitySlots");
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.Booking", b =>
                {
                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.Property<long>("AvailabilitySlotId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "TeacherId", "AvailabilitySlotId");

                    b.HasIndex("AvailabilitySlotId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.EducationStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EducationStages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArabicName = "المرحلة الابتدائية",
                            EnglishName = "Primary Stage"
                        },
                        new
                        {
                            Id = 2,
                            ArabicName = "المرحلة الإعدادية",
                            EnglishName = "Preparatory Stage"
                        },
                        new
                        {
                            Id = 3,
                            ArabicName = "المرحلة الثانوية",
                            EnglishName = "Secondary Stage"
                        },
                        new
                        {
                            Id = 4,
                            ArabicName = "المرحلة الجامعية",
                            EnglishName = "University Stage"
                        });
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.EducationSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EducationSystems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArabicName = "النظام القديم",
                            EnglishName = "Old System"
                        },
                        new
                        {
                            Id = 2,
                            ArabicName = "النظام الحديث",
                            EnglishName = "Modern System"
                        },
                        new
                        {
                            Id = 3,
                            ArabicName = "نظام البكالوريا",
                            EnglishName = "Baccalaureate System"
                        });
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.Favorite", b =>
                {
                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.Governorate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProvinceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Governorates");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ArabicName = "القاهرة",
                            EnglishName = "Cairo",
                            ProvinceId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ArabicName = "الجيزة",
                            EnglishName = "Giza",
                            ProvinceId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            ArabicName = "الأسكندرية",
                            EnglishName = "Alexandria",
                            ProvinceId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            ArabicName = "الدقهلية",
                            EnglishName = "Dakahlia",
                            ProvinceId = 3L
                        },
                        new
                        {
                            Id = 5L,
                            ArabicName = "البحر الأحمر",
                            EnglishName = "Red Sea",
                            ProvinceId = 6L
                        },
                        new
                        {
                            Id = 6L,
                            ArabicName = "البحيرة",
                            EnglishName = "Beheira",
                            ProvinceId = 2L
                        },
                        new
                        {
                            Id = 7L,
                            ArabicName = "الفيوم",
                            EnglishName = "Fayoum",
                            ProvinceId = 5L
                        },
                        new
                        {
                            Id = 8L,
                            ArabicName = "الغربية",
                            EnglishName = "Gharbiya",
                            ProvinceId = 3L
                        },
                        new
                        {
                            Id = 9L,
                            ArabicName = "الإسماعلية",
                            EnglishName = "Ismailia",
                            ProvinceId = 4L
                        },
                        new
                        {
                            Id = 10L,
                            ArabicName = "المنوفية",
                            EnglishName = "Menofia",
                            ProvinceId = 3L
                        },
                        new
                        {
                            Id = 11L,
                            ArabicName = "المنيا",
                            EnglishName = "Minya",
                            ProvinceId = 5L
                        },
                        new
                        {
                            Id = 12L,
                            ArabicName = "القليوبية",
                            EnglishName = "Qaliubiya",
                            ProvinceId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            ArabicName = "الوادي الجديد",
                            EnglishName = "New Valley",
                            ProvinceId = 6L
                        },
                        new
                        {
                            Id = 14L,
                            ArabicName = "السويس",
                            EnglishName = "Suez",
                            ProvinceId = 4L
                        },
                        new
                        {
                            Id = 15L,
                            ArabicName = "شمال سيناء",
                            EnglishName = "North Sinai",
                            ProvinceId = 4L
                        },
                        new
                        {
                            Id = 16L,
                            ArabicName = "جنوب سيناء",
                            EnglishName = "South Sinai",
                            ProvinceId = 4L
                        },
                        new
                        {
                            Id = 17L,
                            ArabicName = "بني سويف",
                            EnglishName = "Beni Suef",
                            ProvinceId = 5L
                        },
                        new
                        {
                            Id = 18L,
                            ArabicName = "بورسعيد",
                            EnglishName = "Port Said",
                            ProvinceId = 6L
                        },
                        new
                        {
                            Id = 19L,
                            ArabicName = "دمياط",
                            EnglishName = "Damietta",
                            ProvinceId = 3L
                        },
                        new
                        {
                            Id = 20L,
                            ArabicName = "الشرقية",
                            EnglishName = "Sharkia",
                            ProvinceId = 4L
                        },
                        new
                        {
                            Id = 21L,
                            ArabicName = "جنوب سيناء",
                            EnglishName = "South Sinai",
                            ProvinceId = 4L
                        },
                        new
                        {
                            Id = 22L,
                            ArabicName = "كفر الشيخ",
                            EnglishName = "Kafr Al Sheikh",
                            ProvinceId = 3L
                        },
                        new
                        {
                            Id = 23L,
                            ArabicName = "مطروح",
                            EnglishName = "Matrouh",
                            ProvinceId = 2L
                        },
                        new
                        {
                            Id = 24L,
                            ArabicName = "الأقصر",
                            EnglishName = "Luxor",
                            ProvinceId = 7L
                        },
                        new
                        {
                            Id = 25L,
                            ArabicName = "قنا",
                            EnglishName = "Qena",
                            ProvinceId = 7L
                        },
                        new
                        {
                            Id = 26L,
                            ArabicName = "شمال سيناء",
                            EnglishName = "North Sinai",
                            ProvinceId = 4L
                        },
                        new
                        {
                            Id = 27L,
                            ArabicName = "سوهاج",
                            EnglishName = "Sohag",
                            ProvinceId = 7L
                        });
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.Province", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ArabicName = "القاهرة الكبرى",
                            EnglishName = "Great Cairo"
                        },
                        new
                        {
                            Id = 2L,
                            ArabicName = "الاسكندرية",
                            EnglishName = "Alexandria"
                        },
                        new
                        {
                            Id = 3L,
                            ArabicName = "الدلتا",
                            EnglishName = "Al-Delta"
                        },
                        new
                        {
                            Id = 4L,
                            ArabicName = "القناة",
                            EnglishName = "Al-Canal"
                        },
                        new
                        {
                            Id = 5L,
                            ArabicName = "شمال الصعيد",
                            EnglishName = "North of Al-Saieed"
                        },
                        new
                        {
                            Id = 6L,
                            ArabicName = "وسط الصعيد",
                            EnglishName = "Middle of Al-Saieed"
                        },
                        new
                        {
                            Id = 7L,
                            ArabicName = "جنوب الصعيد",
                            EnglishName = "South of Al-Saieed"
                        });
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "ARA",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2145),
                            Description = "منهج اللغة العربية واكتساب المهارات اللغوية والنحوية",
                            Name = "اللغة العربية",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2150)
                        },
                        new
                        {
                            Id = 2L,
                            Code = "ENG",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2154),
                            Description = "منهج اللغة الإنجليزية للاتصال والمحادثة والقواعد",
                            Name = "اللغة الإنجليزية",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2154)
                        },
                        new
                        {
                            Id = 3L,
                            Code = "SOC",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2156),
                            Description = "منهج الجغرافيا والتاريخ ومبادئ المواطنة",
                            Name = "الدراسات الاجتماعية",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2156)
                        },
                        new
                        {
                            Id = 4L,
                            Code = "FRN",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2157),
                            Description = "منهج اللغة الأجنبية الثانية - الفرنسية",
                            Name = "اللغة الفرنسية",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2157)
                        },
                        new
                        {
                            Id = 5L,
                            Code = "GER",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2158),
                            Description = "منهج اللغة الأجنبية الثانية - الألمانية",
                            Name = "اللغة الألمانية",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2159)
                        },
                        new
                        {
                            Id = 6L,
                            Code = "ITA",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2160),
                            Description = "منهج اللغة الأجنبية الثانية - الإيطالية",
                            Name = "اللغة الإيطالية",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2160)
                        },
                        new
                        {
                            Id = 7L,
                            Code = "REL",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2161),
                            Description = "منهج التربية الدينية الإسلامية والمسيحية",
                            Name = "التربية الدينية",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2162)
                        },
                        new
                        {
                            Id = 8L,
                            Code = "MAT-AR",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2163),
                            Description = "منهج الرياضيات والحساب باللغة العربية",
                            Name = "الرياضيات",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2163)
                        },
                        new
                        {
                            Id = 9L,
                            Code = "SCI-AR",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2164),
                            Description = "منهج العلوم العامة باللغة العربية",
                            Name = "العلوم",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2164)
                        },
                        new
                        {
                            Id = 10L,
                            Code = "PHY-AR",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2165),
                            Description = "منهج الفيزياء المتقدمة باللغة العربية",
                            Name = "الفيزياء",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2166)
                        },
                        new
                        {
                            Id = 11L,
                            Code = "CHE-AR",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2167),
                            Description = "منهج الكيمياء والتفاعلات باللغة العربية",
                            Name = "الكيمياء",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2167)
                        },
                        new
                        {
                            Id = 12L,
                            Code = "BIO-AR",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2168),
                            Description = "منهج علم الأحياء والبيئة باللغة العربية",
                            Name = "الأحياء",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2169)
                        },
                        new
                        {
                            Id = 13L,
                            Code = "GEO-AR",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2170),
                            Description = "منهج الجيولوجيا وعلوم الأرض باللغة العربية",
                            Name = "الجيولوجيا",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2170)
                        },
                        new
                        {
                            Id = 14L,
                            Code = "MAT-EN",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2171),
                            Description = "Mathematics and algebra syllabus in English",
                            Name = "Math",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2172)
                        },
                        new
                        {
                            Id = 15L,
                            Code = "SCI-EN",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2173),
                            Description = "General Science syllabus in English",
                            Name = "Science",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2177)
                        },
                        new
                        {
                            Id = 16L,
                            Code = "PHY-EN",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2178),
                            Description = "Advanced Physics concepts and mechanics in English",
                            Name = "Physics",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2178)
                        },
                        new
                        {
                            Id = 17L,
                            Code = "CHE-EN",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2179),
                            Description = "Organic and inorganic Chemistry syllabus in English",
                            Name = "Chemistry",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2180)
                        },
                        new
                        {
                            Id = 18L,
                            Code = "BIO-EN",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2181),
                            Description = "Living organisms and Biology syllabus in English",
                            Name = "Biology",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2181)
                        },
                        new
                        {
                            Id = 19L,
                            Code = "HIS",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2182),
                            Description = "منهج التاريخ والحضارات للمرحلة الثانوية",
                            Name = "التاريخ",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2183)
                        },
                        new
                        {
                            Id = 20L,
                            Code = "GEO",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2184),
                            Description = "منهج الجغرافيا السياسية والطبيعية للمرحلة الثانوية",
                            Name = "الجغرافيا",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2184)
                        },
                        new
                        {
                            Id = 21L,
                            Code = "PHI",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2185),
                            Description = "مبادئ التفكير الفلسفي والمنطق الصوري",
                            Name = "الفلسفة والمنطق",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2185)
                        },
                        new
                        {
                            Id = 22L,
                            Code = "PSY",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2187),
                            Description = "دراسة السلوك الإنساني ومبادئ علم الاجتماع",
                            Name = "علم النفس والاجتماع",
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 820, DateTimeKind.Utc).AddTicks(2187)
                        });
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.TeacherSubject", b =>
                {
                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("TeacherId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("TeacherSubjects");
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("NationalId")
                        .HasColumnType("bigint");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccessFailedCount = 0,
                            BirthDate = new DateOnly(1990, 1, 1),
                            ConcurrencyStamp = "92cfbf6d-4931-4c6b-9321-56e21e5de86c",
                            CreatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 736, DateTimeKind.Utc).AddTicks(9258),
                            Email = "mohammed.atef.abdelkader@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            Gender = "M",
                            LastName = "Administrator",
                            LockoutEnabled = false,
                            NationalId = 0L,
                            NormalizedEmail = "MOHAMMED.ATEF.ABDELKADER@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAECguFO8hdBUbQoMvqimkES1sXQFffSrMHdxngOKnpYTa3a4ab0XIAISc2a/PJfdgog==",
                            PhoneNumberConfirmed = false,
                            UpdatedAt = new DateTime(2026, 7, 2, 16, 15, 22, 736, DateTimeKind.Utc).AddTicks(9262),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.UserAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AreaId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            RoleId = 1L
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.Area", b =>
                {
                    b.HasOne("Dars_5ososy_API.Domain.Entities.Governorate", "Governorate")
                        .WithMany()
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.AvailabilitySlot", b =>
                {
                    b.HasOne("Dars_5ososy_API.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dars_5ososy_API.Domain.Entities.EducationStage", "EducationStage")
                        .WithMany()
                        .HasForeignKey("EducationStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dars_5ososy_API.Domain.Entities.EducationSystem", "EducationSystem")
                        .WithMany()
                        .HasForeignKey("EducationSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dars_5ososy_API.Domain.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("EducationStage");

                    b.Navigation("EducationSystem");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Dars_5ososy_API.Domain.Entities.AvailabilitySlot", "AvailabilitySlot")
                        .WithMany()
                        .HasForeignKey("AvailabilitySlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dars_5ososy_API.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dars_5ososy_API.Domain.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AvailabilitySlot");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("Dars_5ososy_API.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dars_5ososy_API.Domain.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.Governorate", b =>
                {
                    b.HasOne("Dars_5ososy_API.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.Image", b =>
                {
                    b.HasOne("Dars_5ososy_API.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Dars_5ososy_API.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.Review", b =>
                {
                    b.HasOne("Dars_5ososy_API.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dars_5ososy_API.Domain.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.TeacherSubject", b =>
                {
                    b.HasOne("Dars_5ososy_API.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dars_5ososy_API.Domain.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Dars_5ososy_API.Domain.Entities.UserAddress", b =>
                {
                    b.HasOne("Dars_5ososy_API.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dars_5ososy_API.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Dars_5ososy_API.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Dars_5ososy_API.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dars_5ososy_API.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Dars_5ososy_API.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
